---
title: "Dolomites, day 2 (co-written with Erin)"
date: 2018-07-06
tags: [dolonice]
---

Our second day in the Dolomites began at 6:30, getting ourselves ready so that we could take off soon after breakfast (since we were again facing a forecast of afternoon thunderstorms).

Since we'd never done any hut-to-hut hiking before, a little elaboration on the huts might be worthwhile. First, they are emphatically _not_ huts. Even Rifugio Croda de Lago, which was the one of the smallest, tightest rifugios we'd seen, still housed at least 30 people (and likely more). They're basically large chalets with bedrooms that tend be

The breakfast spread was impressive, including fresh croissants and hard boiled eggs, along with the classic yogurt and muesli and, of course, meats and cheeses. 

With full stomachs, we continued our path north along the lake through a delightful, wooded route with soft footing and little elevation change - a rarity here! Turning west around the end of the escarpment, we found ourselves suddenly and steeply descending towards the valley floor. Even with hiking poles in hand, the sharp descents were hard on the knees, so we were glad when the path leveled out into a meadow and near the first of few small private cabins we saw today. After another half an hour we made it to a road, which was followed by a rapid ascent through a muddy, forested area; in the Dolomites, what goes down must come up! The trail was lovely but slick after the rains, so when it finally leveled out into a gravel track near the second private cabin (picture below) and slowed its rate of ascent we were glad for that too.

Around 9:30, we arrived at Rifugio Cinque Torri for a tasty cappuccino (Erin says, “that sweet sweet espresso”). The Rifugio is eponymously named for the iconic tower formation that was used heavily during.
WW1, and is now a climbing destination - many climbers were high on the tower in the midst of their multi pitch climbs. 

We can’t really do justice to the views here so the pictures will have to speak for themselves, but safe to say we haven’t become inured to the charms of these mountains yet.

Onward led us up past another Rifugio and gave us views of two more sitting far on top of mountains - Nunavalu from yesterday, and another accessible via funicular from our starting point, Passo Falzarego.

One of our favorite parts of the day was the wildflowers popping out amidst the rocks, grass, and ski lifts, which we hiked under as we continued west, north and underneath our first Rifugio from yesterday, Averau. The path turned north again and descended through a forest until we intersected with a road, which we followed briefly until turning back onto the trail next to a now-abandoned Rifugio (which was creepy inside).

The last stretch of our day brought us up the mountains opposite the road, and gave us a view of much of the hike we just finished. We got to pass through a rock tunnel, and across a huge boulder field, before finally making it to our stop for the night, Rifugio Dibona. Like Cinque Torri, Dibona is a center for climbers, and is also accessible by road so it wasn’t only hikers there with us. We completed the lunch-nap-dinner challenge, stuffing ourselves with a delicious venison ragu (Pat) and spinach ravioli (Erin). 

We ended the evening with a walk and some rock throwing (Pat will be starting a fitness class based solely around throwing rocks) before chatting with our room companion, John, a charming retired gentleman from north England. He shares Pat’s passion for a carbon tax.

Tomorrow is our last day hiking! It will also be our longest, 18km, although perhaps more due to a required detour (a path is out).